FROM maven:3.9.0-eclipse-temurin-17-alpine AS build

WORKDIR /home/app

COPY pom.xml .

COPY src/ src/

RUN mvn -f /home/app/pom.xml clean package -DskipTests -X

EXPOSE 8080

ENTRYPOINT ["mvn", "clean", "spring-boot:run"]
